name: Python Mutation Test

on: 
  pull_request:
    paths:
      - req/*
      - src/*
      - test/*
      - .github/workflows/python-mutation-test.yml
  workflow_dispatch:

jobs:
  pytest:
    name: Mutation Test with Mutmut
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Dependencies and Tools
        run: |
          pip install -r req/requirements.txt --upgrade
          pip install -r req/pytest.txt --upgrade
          pip install --editable .
          pip install mutmut --upgrade
      - name: clone pytest_sort
        run: |
          cp -r src src_mut
          mv src_mut/pytest_sort src_mut/pytest_sort_mut
          sed -i 's/pytest_sort/pytest_sort_mut/g' src_mut/pytest_sort_mut/*.py
          sed -i 's/pytest_sort/pytest_sort_mut/g' test/*.py
      - name: Mutmut
        run: python3 -m mutmut run --no-progress --rerun-all --paths-to-mutate src_mut 
          --runner "pytest -x --assert=plain --sort-mode=fastest --sort-bucket=function"
      - run: python3 -m mutmut results
        if: ${{ always() }}
      - name: Mutmut Report
        if: ${{ always() }}
        run: |
          python3 -m mutmut html
          python3 -m mutmut junitxml > mutation-testing-report.xml
      - name: save-xml-report
        uses: EndBug/add-and-commit@v9
        with:
          add: "mutation-testing-report.xml"
      - name: save-reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Mutation testing report
          path: html
