name: Python Platform Tests

on: 
  push:
    paths:
      - req
      - src
      - test
  pull_request:
    paths:
      - req
      - src
      - test
  workflow_dispatch:

jobs:
  pytest-matrix:
    name: Unit Test with Pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        py: ['3.8','3.9','3.10','3.11','3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Install Dependencies and Tools
        run: |
          pip install -r req/requirements.txt --upgrade
          pip install -r req/pytest.txt --upgrade
      - run: pytest
