name: Python Tests and Scans

on: 
  push:
    paths:
      - .github/workflows/python-test-scan.yml
      - req/**
      - src/**
      - test/**
  pull_request:
    paths:
      - req/**
      - src/**
      - test/**
  workflow_dispatch:

jobs:
  pytest-cov:
    name: Unit Test with Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Dependencies and Tools
        run: |
          python3 -m pip install --upgrade pip
          pip install -r req/requirements.txt --upgrade
          pip install -r req/pytest.txt --upgrade
      - run: pytest --help
      - run: pytest --cov=src --cov-report=json:code-coverage.json
      - name: artifact-html-report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Coverage Report HTML
          path: cov-html
      - name: artifact-json-report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Coverage Report JSON
          path: code-coverage.json
  isort:
    name: Import Checks with ISort
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Dependencies and Tools
        run: |
          python3 -m pip install --upgrade pip
          pip install -r req/requirements.txt --upgrade
          pip install isort --upgrade
      - run: python3 -m isort src --check --diff
      - run: python3 -m isort test --check --diff
        if: ${{ always() }}
  black:
    name: Code Format with Black
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Dependencies and Tools
        run: |
          python3 -m pip install --upgrade pip
          pip install -r req/requirements.txt --upgrade
          pip install black --upgrade
      - run: black --check src --diff
      - run: black --check test --diff
        if: ${{ always() }}
  ruff-fmt:
    name: Code Format with Ruff
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Ruff format
        uses: chartboost/ruff-action@v1
        with:
          src: src test
          args: format --diff
  mypy:
    name: Type Checks with Mypy
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Dependencies and Tools
        run: |
          python3 -m pip install --upgrade pip
          pip install -r req/requirements.txt --upgrade
          pip install -r req/mypy.txt --upgrade
      - run: mypy --python-version 3.8
        if: ${{ always() }}
      - run: mypy --python-version 3.9
        if: ${{ always() }}
      - run: mypy --python-version 3.10
        if: ${{ always() }}
      - run: mypy --python-version 3.11
        if: ${{ always() }}
      - run: mypy --python-version 3.12
        if: ${{ always() }}
  ruff:
    name: Linter Checks with Ruff
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Ruff src
        uses: chartboost/ruff-action@v1
        with:
          src: src
          args: check --show-files
      - name: Ruff src diff
        uses: chartboost/ruff-action@v1
        if: ${{ always() }}
        with:
          src: src
          args: check --diff
      - name: Ruff test
        uses: chartboost/ruff-action@v1
        if: ${{ always() }}
        with:
          src: test
          args: check --show-files
      - name: Ruff test diff
        uses: chartboost/ruff-action@v1
        if: ${{ always() }}
        with:
          src: test
          args: check --diff
