name: Python Mutation Test

on: 
  workflow_dispatch:

# json is created and saved in update-coverage workflow
jobs:
  poodle:
    name: Mutation Test with Poodle
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Dependencies and Tools
        run: |
          python3 -m pip install --upgrade pip
          pip install -r req/requirements.txt --upgrade
          pip install -r req/poodle.txt --upgrade
          pip install --editable .
      - name: Pytest Coverage
        run: pytest --cov=src --cov-context=test
      - run: poodle --html mutation_reports
      - name: Upload Report HTML
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Mutation testing report HTML
          path: mutation_reports