name: Python Tests and Scans

on: 
  push:
    paths:
      - req
      - src
      - test
  pull_request:
    paths:
      - req
      - src
      - test
  workflow_dispatch:

jobs:
  pytest:
    name: Unit Test with Pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Dependencies and Tools
        run: |
          pip install -r req/requirements.txt --upgrade
          pip install -r req/pytest.txt --upgrade
      - run: pytest --help
      - run: pytest --cov=src
      - name: save-json-report
        uses: EndBug/add-and-commit@v9
        with:
          add: "code-coverage.json"
      - name: save-reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Coverage Report
          path: reports/coverage
  isort:
    name: Import Checks with ISort
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Dependencies and Tools
        run: |
          pip install -r req/requirements.txt --upgrade
          pip install isort --upgrade
      - run: python3 -m isort src --check --diff
      - run: python3 -m isort test --check --diff
  black:
    name: Code Format with Black
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Dependencies and Tools
        run: |
          pip install -r req/requirements.txt --upgrade
          pip install black --upgrade
      - run: black --check src --diff
      - run: black --check test --diff
  mypy:
    name: Type Checks with Mypy
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Dependencies and Tools
        run: |
          pip install -r req/requirements.txt --upgrade
          pip install -r req/mypy.txt --upgrade
      - run: mypy src
  ruff:
    name: Linter Checks with Ruff
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: src
